# Cloudflare Pages Configuration
# https://developers.cloudflare.com/pages/configuration/

name = "ai-prompts"

# Pages-specific configuration
[build]
command = "npm run build"
output_directory = ".app/dist"

# Compatibility settings
compatibility_date = "2024-01-01"
compatibility_flags = []

# Environment variables can be set here or in the Cloudflare dashboard
[env.production]
# Add production environment variables here if needed

[env.preview]
# Add preview environment variables here if needed
